setwd("C:/Users/admin/Desktop/137_Creditcard-Fraud-Detection-Dataset")
library(ranger)
library(caret)
library(data.table)
library(ggplot2)
creditcard_data <- read.csv("C:/Users/admin/Desktop/137_Creditcard-Fraud-Detection-Dataset/137_creditcard.csv")
dim(creditcard_data)
head(creditcard_data,6)
tail(creditcard_data,6)
table(creditcard_data$Class)
table(creditcard_data$Time)
summary(creditcard_data$Amount)
names(creditcard_data)
var(creditcard_data$Amount)
sd(creditcard_data$Amount)
plot(creditcard_data$Time,creditcard_data$Amount)
summary(creditcard_data$Time)
boxplot(creditcard_data$Time, main = "Time per second of fraud detection" ,xlab="Customer identity", ylab="Time is seconds")
plot(creditcard_data$Amount,creditcard_data$Class)
#Preprocessing and EDA 
head(creditcard_data)
#feature standardization using scale function
creditcard_data$Amount=scale(creditcard_data$Amount)
NewData=creditcard_data[,-c(1)]

head(NewData)
#split the dataset into train and test with a split ratio of 0.80
library(caTools)
set.seed(123)
data_sample = sample.split(NewData$Class,SplitRatio=0.80)
train_data = subset(NewData,data_sample==TRUE)
test_data = subset(NewData,data_sample==FALSE)
dim(train_data)
dim(test_data)
#Fitting Logistic Regression Model
Logistic_Model=glm(Class~.,test_data,family=binomial())
summary(Logistic_Model)
#Model Prediction
logitMod <- glm(Class ~ V1 + V2 + V3 + V4 + V5 + V6 +V7 + V8 + V9 + V10 + V11 + V12 + V13 + V14 + V15 + V16 + V17 + V18 + V19 + V20 + V21 + V22 + V23 + V24 + V25 + V26 + V27 + V28,data = train_data, family = binomial(link = "logit") )
#predicted scores
predicted <- plogis(predict(logitMod, test_data))
library(InformationValue)
optCutOff <- optimalCutoff(test_data$Class, predicted)[1] 
print(optCutOff*100)
Logistic_Model=glm(Class~.,train_data,family=binomial())
summary(Logistic_Model)
Logistic_Model=glm(Class~.,test_data,family=binomial())
summary(Logistic_Model)
vif(Logistic_Model)
plot(Logistic_Model)
library(pROC)
lr.predict <- predict(Logistic_Model,test_data, probability = TRUE)
auc.gbm = roc(test_data$Class, lr.predict, plot = TRUE, col = "blue")
plot(auc.gbm)
sensitivity(test_data$Class,predicted,threshold = optCutOff)
print(sensitivity)
specificity(test_data$Class, predicted, threshold = optCutOff)
confusionMatrix(train_data$Class,test_data$Class)
Concordance(test_data$Class,predicted)

